name: Validate Build

on:
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Check Directory Structure
      run: ls -R

    - name: Build with Gradle
      working-directory: MinecraftMarraige/MinecraftMarraige/MarriagePaper
      run: gradle build
